### PR TITLE
Minor Tweaks

### PR DESCRIPTION
**Pull request by pruett**
- Some cosmetic things
- Add an `uninstall` switch for the `conf` command that will call `make` with **un** prefixed to the argument.
  - `conf install ruby` > `make ruby`
  - `conf uninstall ruby` > `make unruby`

Making the system modular and reversible are the goals for my config system, perhaps you value similar

### CODE REVIEW

**Comment by pruett** [comment]
actually, ruby 2.1.5 is the latest...i can update

**Comment by jescalan** [comment]
Looks good to me! Thanks for adding this stuff in. Is that weird call syntax really the only way to call a function? Wish it could be cleaner, but if you looked into it and there's no way that wouldn't surprise me haha. Good ol bash.

**Comment by jescalan** [comment]
Let me know when the ruby version upgrade is set and we can marge this up

**Comment by pruett** [comment]
ok @jenius go for it...more PRs coming for you to consider most likely...

**Comment by jescalan** [comment]
decided not to up that ruby version? haha

this is my new version of this lib btw: https://github.com/jescalan/dotfiles

**Comment by pruett** [comment]
nice and clean...here's mine https://github.com/pruett/dotfiles

you rocking vim now too?

**Comment by jescalan** [comment]
Nice! Gotta love that bison wallpaper hahah. Nah I'm using atom. Only use vim for commit messages, otherwise atom is more efficient for me.

**Pull request closed without merging**
